### PR TITLE
CLOWNFISH-39 Public Vector API

### PR DESCRIPTION
**Pull request by nwellnhof**
Fixes CLOWNFISH-39.

One of the changes to make Sort_quicksort work with size_t indices is extremely ugly. We could also use `ssize_t` but this requires a feature test to make it portable.

### CODE REVIEW

**Comment by rectang** [comment]
We have poor test coverage on SortUtils, sadly.  That's not your fault, but because that's the case extensive changes to our sort routines give me the willies.

The sort routines currently use `int32_t` and `uint32_t` for a lot of indexes. Instead of replacing those with `size_t` or `ssize_t`, couldn't we use `int64_t` and `uint64_t` instead?  That way we preserve the current signed behavior and merely need to think about range changes.  I think that's easier to reason about.

Also are we sure that a check for equality to `(size_t)-1` will work under all optimizing compilers?  If we can avoid going down that rabbit hole by using `int64_t` and `uint64_t`, that would make me happy.

**Comment by nwellnhof** [comment]
> We have poor test coverage on SortUtils, sadly. That's not your fault, but because that's the case extensive changes to our sort routines give me the willies.

@rectang Yes, when changing the indexes in quicksort, I found some bugs only after testing with Lucy. It's especially important to test quicksort with lots of duplicate keys. The special handling of keys equal to the pivot is what makes our implementation so complicated and error-prone. But I understand why this is an important optimization.

> The sort routines currently use int32_t and uint32_t for a lot of indexes. Instead of replacing those with size_t or ssize_t, couldn't we use int64_t and uint64_t instead? That way we preserve the current signed behavior and merely need to think about range changes. I think that's easier to reason about.

I'm not worried about the mergesort implementation. But I agree that the changes to quicksort make the implementation more fragile with regard to future changes. Ultimately, I'd like to add a Charmonizer probe for `ssize_t`. But for now, we can use `int64_t` on all platforms. The fact that we can't sort arrays larger than `SIZE_MAX / 2` with a signed type shouldn't be an issue. This only affects byte arrays.

> Also are we sure that a check for equality to (size_t)-1 will work under all optimizing compilers? If we can avoid going down that rabbit hole by using int64_t and uint64_t, that would make me happy.

Technically, this check is OK. Unsigned overflow and conversion from signed to unsigned are well-defined in C (as opposed to signed overflow and conversion from unsigned to signed).

From the C99 spec, section 6.2.5 (9):

> A computation involving unsigned operands can never overflow, because a result that cannot be represented by the resulting unsigned integer type is reduced modulo the number that is one greater than the largest value that can be represented by the resulting type.

Section 6.3.1.3 Signed and unsigned integers:

> When a value with integer type is converted to another integer type other than _Bool, if the value can be represented by the new type, it is unchanged.

> Otherwise, if the new type is unsigned, the value is converted by repeatedly adding or subtracting one more than the maximum value that can be represented in the new type until the value is in the range of the new type.

> Otherwise, the new type is signed and the value cannot be represented in it; either the result is implementation-defined or an implementation-defined signal is raised.

This guarantees that `(size_t)0 - (size_t)1 == (size_t)-1 == SIZE_MAX` and `(size_t)-1 + (size_t)1 == (size_t)0`.

**Comment by rectang** [comment]
It's a bit touchy to suggest this now that you've done a bunch of work on our quicksort routine, but it is now barely used and could be replaced entirely with the system `qsort`. The only differentiating feature of `Sort_quicksort` is that the comparison routine supports a `context` argument, but none of the remaining call sites take advantage of that feature.

**Comment by nwellnhof** [comment]
> It's a bit touchy to suggest this now that you've done a bunch of work on our quicksort routine, but it is now barely used and could be replaced entirely with the system qsort.

I don't have a strong opinion on that.

**Comment by rectang** [comment]
> I don't have a strong opinion on that.

In that case, let's lighten our maintenance burden and remove `Sort_quicksort`.

There are three call sites in Lucy which will need to be changed.  I suggest using `qsort` in HeatMap.c and TestBitVector.c, and `Sort_mergesort` in Inversion.c.

I've reviewed the changes to `Sort_mergesort` and they look good to me.  If we remove `Sort_quicksort`, then we don't need to worry about its correctness any more. With that issue resolved, +1 to merge this pull request!

**Comment by nwellnhof** [comment]
> There are three call sites in Lucy which will need to be changed. I suggest using qsort in HeatMap.c and TestBitVector.c, and Sort_mergesort in Inversion.c.

There's one more site in `IndexManager.c` now that it doesn't use `Vec_Sort`. I converted all of them to `qsort`.

Maybe we should add `Vec_Unstable_Sort` that uses the system `qsort`? This might be much more efficient than `Sort_mergesort`.

**Comment by rectang** [comment]
> Maybe we should add `Vec_Unstable_Sort` that uses the system 
> `qsort`? This might be much more efficient than `Sort_mergesort`.

I'm skeptical that the improvements would be that great because of the large per-comparison constant factors. If sort speed is a bottleneck you're going to want something which avoids the indirection of the function-pointer comparison routine and the `Compare_To` method calls. A custom quicksort with hard-coded integer comparison is going to blow away _any_ general solution. People can always allocate their own `cfish_Obj**` C array and `qsort` that, and if that's not enough they can keep optimizing.

This reminds me of all the different Analyzer designs Lucy went through trying to find something that would be reasonably fast for a host Analyzer implementation. Nothing that was flexible was also fast.  In the end, it seemed better to prioritize flexibility and accept that optimizing for speed requires dropping into C.

**Comment by nwellnhof** [comment]
> If sort speed is a bottleneck you're going to want something which avoids the indirection of the function-pointer comparison routine and the Compare_To method calls. A custom quicksort with hard-coded integer comparison is going to blow away any general solution.

This is a good point, but `Vec_Unstable_Sort` would add only a few lines of code and at least it wouldn't need any extra memory.

**Pull request merged**
